-- Seed 30 Categories for Electronics & Home Appliances
INSERT INTO Category (CategoryCode, DisplayName, IsActive) VALUES 
('LTP', 'Laptop & Máy tính xách tay', 1),
('PC', 'Máy tính để bàn (PC)', 1),
('MNT', 'Màn hình máy tính', 1),
('PRN', 'Máy in & Thiết bị văn phòng', 1),
('SMT', 'Điện thoại thông minh', 1),
('TBL', 'Máy tính bảng', 1),
('ACC', 'Phụ kiện điện thoại', 1),
('TV', 'Tivi & Thiết bị giải trí', 1),
('SND', 'Loa & Thiết bị âm thanh', 1),
('CAM', 'Máy ảnh & Máy quay phim', 1),
('REF', 'Tủ lạnh & Tủ đông', 1),
('WSH', 'Máy giặt & Máy sấy', 1),
('AC', 'Máy lạnh & Điều hòa', 1),
('MW', 'Lò vi sóng & Lò nướng', 1),
('KCH', 'Thiết bị nhà bếp', 1),
('VAC', 'Máy hút bụi & Robot hút bụi', 1),
('FAN', 'Quạt & Thiết bị làm mát', 1),
('WTR', 'Máy lọc nước', 1),
('IRN', 'Bàn là & Máy guồng', 1),
('HME', 'Đồ gia dụng thông minh', 1),
('GAM', 'Máy chơi game (Console)', 1),
('HDPH', 'Tai nghe & Gaming Gear', 1),
('NET', 'Thiết bị mạng (Router/Switch)', 1),
('STO', 'Thiết bị lưu trữ (Ổ cứng/USB)', 1),
('BAT', 'Pin & Bộ sạc dự phòng', 1),
('LGT', 'Đèn & Thiết bị chiếu sáng', 1),
('TOOL', 'Dụng cụ cầm tay & Máy móc', 1),
('SEC', 'Camera an ninh & Chống trộm', 1),
('WAT', 'Đồng hồ thông minh (Smartwatch)', 1),
('MISC', 'Linh kiện điện tử khác', 1);
