@startuml Deployment_HeThong
title Real deployment diagram
node User_PC_Windows {
  artifact WarePro_exe as Exe
  artifact appsettings_json as Config
  artifact runtime_dlls as Dlls
}
node SQL_Server_Node {
  database ProductManagement_DB as Db
}
folder Import_Export_Folder as Files
Exe --> Config
Exe --> Dlls
Exe --> Db
Exe --> Files
@enduml
