@startwbs Sitemap_ManHinh
* QuanLyHangHoa WPF
** Dang nhap
*** LoginView
*** ChangePasswordView
** Tong quan
*** DashboardView
** Kho va san pham
*** ProductView
*** ProductSerialView
*** InventoryView
*** StockInView
*** StockOutView
*** StockTransferView
*** StockAdjustmentView
*** StockCountView
*** OpeningBalanceImportView
** Hoa don
*** PurchaseInvoiceView
*** SalesInvoiceView
** Bao hanh
*** WarrantyView
*** WarrantyCoverageView
*** WarrantyClaimView
*** WarrantyPrintWindow
** Danh muc
*** CategoryView
*** BrandView
*** UnitView
*** SupplierView
*** CustomerView
*** ProductUnitView
** Bao cao va truy vet
*** ReportView
*** Bao cao ngay
*** Nhap xuat ton
*** StockLedger
*** Truy vet san pham / serial
** Quan tri
*** AppUserView
*** AuditLogView
@endwbs
