// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHangHoa.Data;

#nullable disable

namespace QuanLyHangHoa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407115050_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("QuanLyHangHoa.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Filco"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Máy tính xách tay"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Linh kiện & Phụ kiện"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Màn hình"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Âm thanh"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "",
                            IsDeleted = false,
                            Name = "Khách lẻ",
                            Phone = ""
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Quản trị viên Hệ thống",
                            PasswordHash = "admin",
                            Position = "Giám Đốc Cửa Hàng",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1995, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn Thu Ngân",
                            PasswordHash = "staff1",
                            Position = "Thu Ngân",
                            Role = "Staff",
                            Username = "staff1"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1996, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thị Kiểm Kho",
                            PasswordHash = "staff2",
                            Position = "Thủ Kho",
                            Role = "Staff",
                            Username = "staff2"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1997, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Bảo Hành",
                            PasswordHash = "staff3",
                            Position = "Nhân viên Bảo hành",
                            Role = "Staff",
                            Username = "staff3"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1998, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Sale",
                            PasswordHash = "staff4",
                            Position = "Nhân viên Part-time",
                            Role = "Staff",
                            Username = "staff4"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            IsDeleted = false,
                            Name = "Laptop Dell XPS 15",
                            Notes = "Hàng đắt tiền, cấu hình cao",
                            Origin = "Mỹ",
                            Quantity = 20,
                            UnitId = 1,
                            UnitPrice = 35000000m,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "Chuột Logitech G502",
                            Notes = "Chuột gaming siêu nhạy",
                            Origin = "Trung Quốc",
                            Quantity = 150,
                            UnitId = 1,
                            UnitPrice = 1200000m,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 4,
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "Bàn phím cơ Filco Majestouch",
                            Notes = "Chuyên dụng cho Lập trình viên",
                            Origin = "Nhật Bản",
                            Quantity = 35,
                            UnitId = 1,
                            UnitPrice = 3200000m,
                            WarrantyMonths = 60
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 3,
                            IsDeleted = false,
                            Name = "Màn hình Dell UltraSharp 27",
                            Notes = "Đồ hoạ cực đỉnh",
                            Origin = "Mỹ",
                            Quantity = 50,
                            UnitId = 1,
                            UnitPrice = 9500000m,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            CategoryId = 4,
                            IsDeleted = false,
                            Name = "Tai nghe kiểm âm Sony MDR-7506",
                            Notes = "Tai nghe studio chuẩn",
                            Origin = "Nhật Bản",
                            Quantity = 45,
                            UnitId = 1,
                            UnitPrice = 2800000m,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "Bàn phím cơ Logitech G Pro X",
                            Notes = "Bàn phím TKL chuyên eSports",
                            Origin = "Trung Quốc",
                            Quantity = 60,
                            UnitId = 1,
                            UnitPrice = 2500000m,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            CategoryId = 3,
                            IsDeleted = false,
                            Name = "Màn hình cong Dell S3221QS",
                            Notes = "Màn hình 4K 32 inch",
                            Origin = "Mỹ",
                            Quantity = 25,
                            UnitId = 1,
                            UnitPrice = 11500000m,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            CategoryId = 1,
                            IsDeleted = false,
                            Name = "Laptop Dell Inspiron 15",
                            Notes = "Laptop văn phòng quốc dân",
                            Origin = "Mỹ",
                            Quantity = 40,
                            UnitId = 1,
                            UnitPrice = 18000000m,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            CategoryId = 4,
                            IsDeleted = false,
                            Name = "Tai nghe không dây Sony WH-1000XM4",
                            Notes = "Chống ồn chủ động đỉnh cao",
                            Origin = "Nhật Bản",
                            Quantity = 70,
                            UnitId = 1,
                            UnitPrice = 6500000m,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "Chuột không dây Logitech MX Master 3S",
                            Notes = "Dòng chuột làm việc chuyên nghiệp",
                            Origin = "Trung Quốc",
                            Quantity = 100,
                            UnitId = 1,
                            UnitPrice = 2300000m,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "Bàn phím không dây Logitech MX Keys",
                            Notes = "Thiết kế mỏng, gõ êm ái",
                            Origin = "Trung Quốc",
                            Quantity = 55,
                            UnitId = 1,
                            UnitPrice = 2200000m,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            CategoryId = 4,
                            IsDeleted = false,
                            Name = "Loa Bluetooth Sony SRS-XB13",
                            Notes = "Nhỏ gọn, âm thanh Extra Bass",
                            Origin = "Trung Quốc",
                            Quantity = 120,
                            UnitId = 1,
                            UnitPrice = 1200000m,
                            WarrantyMonths = 12
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            CategoryId = 3,
                            IsDeleted = false,
                            Name = "Màn hình Dell Alienware AW2521H",
                            Notes = "Màn hình Gaming 360Hz",
                            Origin = "Mỹ",
                            Quantity = 15,
                            UnitId = 1,
                            UnitPrice = 14000000m,
                            WarrantyMonths = 36
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "Máy ảnh Sony Alpha A7 III",
                            Notes = "Máy ảnh Mirrorless Full-frame",
                            Origin = "Nhật Bản",
                            Quantity = 10,
                            UnitId = 1,
                            UnitPrice = 45000000m,
                            WarrantyMonths = 24
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 1,
                            CategoryId = 1,
                            IsDeleted = false,
                            Name = "Laptop Dell Alienware m15 R7",
                            Notes = "Siêu phẩm laptop gaming 2026",
                            Origin = "Mỹ",
                            Quantity = 5,
                            UnitId = 1,
                            UnitPrice = 65000000m,
                            WarrantyMonths = 24
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockInDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockOutDetailId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("StockInDetailId");

                    b.HasIndex("StockOutDetailId");

                    b.ToTable("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SupplierId");

                    b.ToTable("StockIns");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockInId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockInId");

                    b.ToTable("StockInDetails");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("StockOuts");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExportPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockOutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockOutId");

                    b.ToTable("StockOutDetails");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "HCM",
                            IsDeleted = false,
                            Name = "Công ty Dell Việt Nam",
                            Phone = "028-1234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hà Nội",
                            IsDeleted = false,
                            Name = "Phân Phối Logitech SEA",
                            Phone = "024-9876543"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Cái"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Chiếc"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Bộ"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Hộp"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Warranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductSerialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductSerialId")
                        .IsUnique();

                    b.ToTable("Warranties");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("ProductSerials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockInDetail", "StockInDetail")
                        .WithMany("ProductSerials")
                        .HasForeignKey("StockInDetailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyHangHoa.Models.StockOutDetail", "StockOutDetail")
                        .WithMany("ProductSerials")
                        .HasForeignKey("StockOutDetailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("StockInDetail");

                    b.Navigation("StockOutDetail");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Employee", "Employee")
                        .WithMany("StockIns")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Supplier", "Supplier")
                        .WithMany("StockIns")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInDetail", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockIn", "StockIn")
                        .WithMany("StockInDetails")
                        .HasForeignKey("StockInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockIn");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Customer", "Customer")
                        .WithMany("StockOuts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Employee", "Employee")
                        .WithMany("StockOuts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutDetail", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockOut", "StockOut")
                        .WithMany("StockOutDetails")
                        .HasForeignKey("StockOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Warranty", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithOne("Warranty")
                        .HasForeignKey("QuanLyHangHoa.Models.Warranty", "ProductSerialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSerial");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Customer", b =>
                {
                    b.Navigation("StockOuts");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Employee", b =>
                {
                    b.Navigation("StockIns");

                    b.Navigation("StockOuts");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.Navigation("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.Navigation("StockInDetails");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInDetail", b =>
                {
                    b.Navigation("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.Navigation("StockOutDetails");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutDetail", b =>
                {
                    b.Navigation("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Supplier", b =>
                {
                    b.Navigation("StockIns");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
