// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHangHoa.Data;

#nullable disable

namespace QuanLyHangHoa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429194943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("QuanLyHangHoa.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 29, 19, 49, 42, 959, DateTimeKind.Utc).AddTicks(2634),
                            FailedLoginCount = 0,
                            FullName = "Administrator",
                            IsActive = true,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$EhOhp6Ou8HHYkOQVfvMPueoumS/rQ9SCd61tFsTvCkF0ufkWifzMO",
                            RoleCode = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("EntityName", "EntityId", "PerformedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandCode")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandCode = "DELL",
                            DisplayName = "Dell",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            BrandCode = "SONY",
                            DisplayName = "Sony",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryCode = "LAPTOP",
                            DisplayName = "Laptop",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryCode = "ACCESSORY",
                            DisplayName = "Linh kiện",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.InvoicePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurchaseInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceivedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalesInvoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DefaultUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSerialTracked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarrantyPeriodMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefaultUnitId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentWarehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastStockInLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastStockOutLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWarehouseId");

                    b.HasIndex("LastStockInLineId");

                    b.HasIndex("LastStockOutLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPurchaseUnit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSalesUnit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("ProductId", "UnitId")
                        .IsUnique();

                    b.ToTable("ProductUnits");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockInId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.HasIndex("StockInId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockInLineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("StockInLineId");

                    b.HasIndex("UnitId");

                    b.ToTable("PurchaseInvoiceLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockOutId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.HasIndex("StockOutId");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockOutLineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("StockOutLineId");

                    b.HasIndex("UnitId");

                    b.ToTable("SalesInvoiceLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceDocumentCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenceDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceDocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdjustmentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantityDelta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductSerialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityDelta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSerialId");

                    b.ToTable("StockAdjustmentLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OnHandQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("StockBalances");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CountedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SystemQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VarianceQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SessionId");

                    b.ToTable("StockCountLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CountDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockCountSessions");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentCode")
                        .IsUnique();

                    b.HasIndex("PostedBy");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockIns");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockInId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockInId");

                    b.HasIndex("UnitId");

                    b.ToTable("StockInLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductSerialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostedBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSerialId");

                    b.HasIndex("SourceDocumentType", "SourceDocumentId");

                    b.HasIndex("WarehouseId", "ProductId", "PostedAt");

                    b.ToTable("StockLedgers");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DocumentCode")
                        .IsUnique();

                    b.HasIndex("PostedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockOuts");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockOutId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockOutId");

                    b.HasIndex("UnitId");

                    b.ToTable("StockOutLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierCode")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitCode")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Cái",
                            IsActive = true,
                            UnitCode = "PCS"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Bộ",
                            IsActive = true,
                            UnitCode = "SET"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseCode")
                        .IsUnique();

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Main Warehouse",
                            IsActive = true,
                            IsDefault = true,
                            WarehouseCode = "WH01"
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerResult")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessingNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductSerialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplacementSerialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReplacementStockOutId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalConclusion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyCoverageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ClaimCode")
                        .IsUnique();

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("ProductSerialId");

                    b.HasIndex("ReplacementSerialId");

                    b.HasIndex("ReplacementStockOutId");

                    b.HasIndex("WarrantyCoverageId");

                    b.ToTable("WarrantyClaims");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverageStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductSerialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalesInvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WarrantyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WarrantyStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductSerialId")
                        .IsUnique();

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("WarrantyCoverages");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AppUser", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AuditLog", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.InvoicePayment", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany()
                        .HasForeignKey("PurchaseInvoiceId");

                    b.HasOne("QuanLyHangHoa.Models.SalesInvoice", "SalesInvoice")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceId");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Unit", "DefaultUnit")
                        .WithMany()
                        .HasForeignKey("DefaultUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Unit", null)
                        .WithMany("Products")
                        .HasForeignKey("UnitId");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("DefaultUnit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "CurrentWarehouse")
                        .WithMany("ProductSerials")
                        .HasForeignKey("CurrentWarehouseId");

                    b.HasOne("QuanLyHangHoa.Models.StockInLine", "LastStockInLine")
                        .WithMany("ProductSerials")
                        .HasForeignKey("LastStockInLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockOutLine", "LastStockOutLine")
                        .WithMany("ProductSerials")
                        .HasForeignKey("LastStockOutLineId");

                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("ProductSerials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWarehouse");

                    b.Navigation("LastStockInLine");

                    b.Navigation("LastStockOutLine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductUnit", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("ProductUnits")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("ProductUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.StockIn", "StockIn")
                        .WithMany()
                        .HasForeignKey("StockInId");

                    b.HasOne("QuanLyHangHoa.Models.Supplier", "Supplier")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockIn");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoiceLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockInLine", "StockInLine")
                        .WithMany()
                        .HasForeignKey("StockInLineId");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("StockInLine");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoice", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Customer", "Customer")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockOut", "StockOut")
                        .WithMany()
                        .HasForeignKey("StockOutId");

                    b.Navigation("Customer");

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoiceLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockOutLine", "StockOutLine")
                        .WithMany()
                        .HasForeignKey("StockOutLineId");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");

                    b.Navigation("StockOutLine");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustment", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany()
                        .HasForeignKey("PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Poster");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustmentLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.StockAdjustment", "StockAdjustment")
                        .WithMany("Lines")
                        .HasForeignKey("AdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithMany()
                        .HasForeignKey("ProductSerialId");

                    b.Navigation("Product");

                    b.Navigation("ProductSerial");

                    b.Navigation("StockAdjustment");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockBalance", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany("StockBalances")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockCountSession", "StockCountSession")
                        .WithMany("Lines")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockCountSession");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountSession", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany()
                        .HasForeignKey("PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Poster");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("CreatedStockIns")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany()
                        .HasForeignKey("PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Supplier", "Supplier")
                        .WithMany("StockIns")
                        .HasForeignKey("SupplierId");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Poster");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockIn", "StockIn")
                        .WithMany("Lines")
                        .HasForeignKey("StockInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockIn");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockLedger", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany("PostedLedgers")
                        .HasForeignKey("PostedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockLedgers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithMany()
                        .HasForeignKey("ProductSerialId");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poster");

                    b.Navigation("Product");

                    b.Navigation("ProductSerial");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("CreatedStockOuts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Customer", "Customer")
                        .WithMany("StockOuts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany()
                        .HasForeignKey("PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("Poster");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.StockOut", "StockOut")
                        .WithMany("Lines")
                        .HasForeignKey("StockOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockOut");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyClaim", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithMany()
                        .HasForeignKey("ProductSerialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ReplacementSerial")
                        .WithMany()
                        .HasForeignKey("ReplacementSerialId");

                    b.HasOne("QuanLyHangHoa.Models.StockOut", "ReplacementStockOut")
                        .WithMany()
                        .HasForeignKey("ReplacementStockOutId");

                    b.HasOne("QuanLyHangHoa.Models.WarrantyCoverage", "WarrantyCoverage")
                        .WithMany("Claims")
                        .HasForeignKey("WarrantyCoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Processor");

                    b.Navigation("ProductSerial");

                    b.Navigation("ReplacementSerial");

                    b.Navigation("ReplacementStockOut");

                    b.Navigation("WarrantyCoverage");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyCoverage", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithOne("WarrantyCoverage")
                        .HasForeignKey("QuanLyHangHoa.Models.WarrantyCoverage", "ProductSerialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyHangHoa.Models.SalesInvoice", "SalesInvoice")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceId");

                    b.Navigation("Customer");

                    b.Navigation("ProductSerial");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AppUser", b =>
                {
                    b.Navigation("CreatedStockIns");

                    b.Navigation("CreatedStockOuts");

                    b.Navigation("PostedLedgers");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Customer", b =>
                {
                    b.Navigation("SalesInvoices");

                    b.Navigation("StockOuts");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.Navigation("ProductSerials");

                    b.Navigation("ProductUnits");

                    b.Navigation("StockBalances");

                    b.Navigation("StockLedgers");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.Navigation("WarrantyCoverage");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountSession", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInLine", b =>
                {
                    b.Navigation("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutLine", b =>
                {
                    b.Navigation("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseInvoices");

                    b.Navigation("StockIns");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Unit", b =>
                {
                    b.Navigation("ProductUnits");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Warehouse", b =>
                {
                    b.Navigation("ProductSerials");

                    b.Navigation("StockBalances");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyCoverage", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
