// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyHangHoa.Data;

#nullable disable

namespace QuanLyHangHoa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyHangHoa.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("LastPasswordChangedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__AppUser__3214EC07BB2116D3");

                    b.HasIndex(new[] { "CreatedBy" }, "IX_AppUser_CreatedBy");

                    b.HasIndex(new[] { "Username" }, "UX_AppUser_Username")
                        .IsUnique();

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC07718D8FB1");

                    b.HasIndex("PerformedBy");

                    b.HasIndex(new[] { "EntityName", "EntityId", "PerformedAt" }, "IX_AuditLog_Entity");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Brand__3214EC07FFE55213");

                    b.HasIndex(new[] { "BrandCode" }, "UX_Brand_BrandCode")
                        .IsUnique();

                    b.ToTable("Brand", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC077A60AC54");

                    b.HasIndex(new[] { "CategoryCode" }, "UX_Category_CategoryCode")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Customer__3214EC073FBB68C6");

                    b.HasIndex(new[] { "CustomerCode" }, "UX_Customer_CustomerCode")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DefaultUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSerialTracked")
                        .HasColumnType("bit");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarrantyPeriodMonths")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Product__3214EC07522A03D9");

                    b.HasIndex("DefaultUnitId");

                    b.HasIndex(new[] { "BrandId" }, "IX_Product_BrandId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Product_CategoryId");

                    b.HasIndex(new[] { "ProductCode" }, "UX_Product_ProductCode")
                        .IsUnique();

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CurrentWarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("LastStockInLineId")
                        .HasColumnType("int");

                    b.Property<int?>("LastStockOutLineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("StockTransferLineId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProductS__3214EC07227D15E8");

                    b.HasIndex("CurrentWarehouseId");

                    b.HasIndex("LastStockInLineId");

                    b.HasIndex("LastStockOutLineId");

                    b.HasIndex("StockTransferLineId");

                    b.HasIndex(new[] { "CurrentStatus" }, "IX_ProductSerial_CurrentStatus");

                    b.HasIndex(new[] { "ProductId" }, "IX_ProductSerial_ProductId");

                    b.HasIndex(new[] { "SerialNumber" }, "UX_ProductSerial_SerialNumber")
                        .IsUnique();

                    b.ToTable("ProductSerial", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPurchaseUnit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSalesUnit")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProductU__3214EC077420ED44");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "ProductId" }, "UX_ProductUnit_BaseUnit")
                        .IsUnique()
                        .HasFilter("IsBaseUnit = 1");

                    b.HasIndex(new[] { "ProductId", "UnitId" }, "UX_ProductUnit_Product_Unit")
                        .IsUnique();

                    b.ToTable("ProductUnit", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unpaid");

                    b.Property<int?>("StockInId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Purchase__3214EC0788F7D39F");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StockInId");

                    b.HasIndex("SupplierId");

                    b.HasIndex(new[] { "InvoiceDate" }, "IX_PurchaseInvoice_InvoiceDate");

                    b.HasIndex(new[] { "InvoiceCode" }, "UX_PurchaseInvoice_InvoiceCode")
                        .IsUnique();

                    b.ToTable("PurchaseInvoice", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseInvoice_PaymentStatus", "[PaymentStatus] IN ('Unpaid', 'PartiallyPaid', 'Paid', 'Overdue')");
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("StockInLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Purchase__3214EC07D7329CC8");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("StockInLineId");

                    b.HasIndex("UnitId");

                    b.ToTable("PurchaseInvoiceLine", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unpaid");

                    b.Property<int?>("StockOutId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__SalesInv__3214EC07631EEA74");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StockOutId");

                    b.HasIndex(new[] { "InvoiceDate" }, "IX_SalesInvoice_InvoiceDate");

                    b.HasIndex(new[] { "InvoiceCode" }, "UX_SalesInvoice_InvoiceCode")
                        .IsUnique();

                    b.ToTable("SalesInvoice", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalesInvoice_PaymentStatus", "[PaymentStatus] IN ('Unpaid', 'PartiallyPaid', 'Paid', 'Overdue')");
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("StockOutLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__SalesInv__3214EC07959093CA");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("StockOutLineId");

                    b.HasIndex("UnitId");

                    b.ToTable("SalesInvoiceLine", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReferenceDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceDocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockAdj__3214EC07AF8EB3B2");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostedBy");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "DocumentCode" }, "UX_StockAdjustment_DocumentCode")
                        .IsUnique();

                    b.ToTable("StockAdjustment", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseQuantityDelta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductSerialId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityDelta")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__StockAdj__3214EC075A0DD95F");

                    b.HasIndex("AdjustmentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSerialId");

                    b.ToTable("StockAdjustmentLine", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvailableQuantity")
                        .IsConcurrencyToken()
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OnHandQuantity")
                        .IsConcurrencyToken()
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReservedQuantity")
                        .IsConcurrencyToken()
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockBal__3214EC074E13DD5E");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "WarehouseId", "ProductId" }, "UX_StockBalance_Warehouse_Product")
                        .IsUnique();

                    b.ToTable("StockBalance", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CountedQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("SystemQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("VarianceQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__StockCou__3214EC07D1A91334");

                    b.HasIndex("ProductId");

                    b.HasIndex("SessionId");

                    b.ToTable("StockCountLine", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CountDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("int");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockCou__3214EC07BB80C561");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostedBy");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "SessionCode" }, "UX_StockCountSession_SessionCode")
                        .IsUnique();

                    b.ToTable("StockCountSession", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ImportDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("int");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockIn__3214EC07786210D8");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostedBy");

                    b.HasIndex(new[] { "ImportDate" }, "IX_StockIn_ImportDate");

                    b.HasIndex(new[] { "SupplierId" }, "IX_StockIn_SupplierId");

                    b.HasIndex(new[] { "WarehouseId", "PostedAt" }, "IX_StockIn_Warehouse_ProductLookup");

                    b.HasIndex(new[] { "DocumentCode" }, "UX_StockIn_DocumentCode")
                        .IsUnique();

                    b.ToTable("StockIn", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockIn_PurposeCode", "[PurposeCode] IN ('Purchase', 'OpeningBalance', 'Adjustment')");
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DraftSerials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StockInId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__StockInL__3214EC0700E37989");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockInId");

                    b.HasIndex("UnitId");

                    b.ToTable("StockInLine", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PostedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("PostedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductSerialId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SourceDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockLed__3214EC072689E89F");

                    b.HasIndex("PostedBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSerialId");

                    b.HasIndex(new[] { "SourceDocumentType", "SourceDocumentId" }, "IX_StockLedger_SourceDocument");

                    b.HasIndex(new[] { "WarehouseId", "ProductId", "PostedAt" }, "IX_StockLedger_Warehouse_Product_PostedAt");

                    b.ToTable("StockLedger", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExportDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("int");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StockOut__3214EC073AFD26FA");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PostedBy");

                    b.HasIndex(new[] { "CustomerId" }, "IX_StockOut_CustomerId");

                    b.HasIndex(new[] { "ExportDate" }, "IX_StockOut_ExportDate");

                    b.HasIndex(new[] { "WarehouseId", "PostedAt" }, "IX_StockOut_Warehouse_ProductLookup");

                    b.HasIndex(new[] { "DocumentCode" }, "UX_StockOut_DocumentCode")
                        .IsUnique();

                    b.ToTable("StockOut", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockOut_PurposeCode", "[PurposeCode] IN ('Sale', 'WarrantyReplacement', 'Adjustment')");
                        });
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DraftSerials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StockOutId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__StockOut__3214EC07BD561A98");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockOutId");

                    b.HasIndex("UnitId");

                    b.ToTable("StockOutLine", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FromWarehouseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ToWarehouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_StockTransfer");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("PostedBy");

                    b.HasIndex("ToWarehouseId");

                    b.HasIndex(new[] { "DocumentCode" }, "UX_StockTransfer_DocumentCode")
                        .IsUnique();

                    b.ToTable("StockTransfer", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockTransferLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseQuantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StockTransferId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_StockTransferLine");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockTransferId");

                    b.HasIndex("UnitId");

                    b.ToTable("StockTransferLine", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Supplier__3214EC0720C79339");

                    b.HasIndex(new[] { "SupplierCode" }, "UX_Supplier_SupplierCode")
                        .IsUnique();

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Unit__3214EC07F52055D4");

                    b.HasIndex(new[] { "UnitCode" }, "UX_Unit_UnitCode")
                        .IsUnique();

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Warehous__3214EC0700E1A1FD");

                    b.HasIndex(new[] { "IsDefault" }, "UX_Warehouse_SingleDefault")
                        .IsUnique()
                        .HasFilter("IsDefault = 1");

                    b.HasIndex(new[] { "WarehouseCode" }, "UX_Warehouse_WarehouseCode")
                        .IsUnique();

                    b.ToTable("Warehouse", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("ClaimCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ClosedDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ManufacturerExpectedReturnDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ManufacturerResult")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ManufacturerTrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProblemDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProductSerialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ReplacementSerialId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplacementStockOutId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TechnicalConclusion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("WarrantyCoverageId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Warranty__3214EC07EDE89108");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("ReplacementSerialId");

                    b.HasIndex("ReplacementStockOutId");

                    b.HasIndex(new[] { "WarrantyCoverageId" }, "IX_WarrantyClaim_CoverageId");

                    b.HasIndex(new[] { "ClaimCode" }, "UX_WarrantyClaim_ClaimCode")
                        .IsUnique();

                    b.HasIndex(new[] { "ProductSerialId" }, "UX_WarrantyClaim_OpenClaim_PerSerial");

                    b.ToTable("WarrantyClaim", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverageStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSerialId")
                        .HasColumnType("int");

                    b.Property<int?>("SalesInvoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WarrantyEndDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("WarrantyStartDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id")
                        .HasName("PK__Warranty__3214EC07B813D31B");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex(new[] { "CustomerId" }, "IX_WarrantyCoverage_CustomerId");

                    b.HasIndex(new[] { "ProductSerialId" }, "UX_WarrantyCoverage_Active_PerSerial")
                        .IsUnique()
                        .HasFilter("CoverageStatus = 'Active'");

                    b.ToTable("WarrantyCoverage", (string)null);
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AppUser", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("InverseCreator")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_AppUser_CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AuditLog", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Performer")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLog_PerformedBy");

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Brand");

                    b.HasOne("QuanLyHangHoa.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_Category");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "DefaultUnit")
                        .WithMany("Products")
                        .HasForeignKey("DefaultUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_DefaultUnit");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("DefaultUnit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "CurrentWarehouse")
                        .WithMany("ProductSerials")
                        .HasForeignKey("CurrentWarehouseId")
                        .HasConstraintName("FK_ProductSerial_CurrentWarehouse");

                    b.HasOne("QuanLyHangHoa.Models.StockInLine", "LastStockInLine")
                        .WithMany("ProductSerials")
                        .HasForeignKey("LastStockInLineId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductSerial_LastStockInLine");

                    b.HasOne("QuanLyHangHoa.Models.StockOutLine", "LastStockOutLine")
                        .WithMany("ProductSerials")
                        .HasForeignKey("LastStockOutLineId")
                        .HasConstraintName("FK_ProductSerial_LastStockOutLine");

                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("ProductSerials")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductSerial_Product");

                    b.HasOne("QuanLyHangHoa.Models.StockTransferLine", "StockTransferLine")
                        .WithMany("ProductSerials")
                        .HasForeignKey("StockTransferLineId")
                        .HasConstraintName("FK_ProductSerial_StockTransferLine");

                    b.Navigation("CurrentWarehouse");

                    b.Navigation("LastStockInLine");

                    b.Navigation("LastStockOutLine");

                    b.Navigation("Product");

                    b.Navigation("StockTransferLine");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductUnit", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithOne("ProductUnit")
                        .HasForeignKey("QuanLyHangHoa.Models.ProductUnit", "ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductUnit_Product");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("ProductUnits")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductUnit_Unit");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoice_CreatedBy");

                    b.HasOne("QuanLyHangHoa.Models.StockIn", "StockIn")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("StockInId")
                        .HasConstraintName("FK_PurchaseInvoice_StockIn");

                    b.HasOne("QuanLyHangHoa.Models.Supplier", "Supplier")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoice_Supplier");

                    b.Navigation("Creator");

                    b.Navigation("StockIn");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoiceLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("PurchaseInvoiceLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoiceLine_Product");

                    b.HasOne("QuanLyHangHoa.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseInvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoiceLine_Invoice");

                    b.HasOne("QuanLyHangHoa.Models.StockInLine", "StockInLine")
                        .WithMany("PurchaseInvoiceLines")
                        .HasForeignKey("StockInLineId")
                        .HasConstraintName("FK_PurchaseInvoiceLine_StockInLine");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("PurchaseInvoiceLines")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseInvoiceLine_Unit");

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("StockInLine");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoice", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoice_CreatedBy");

                    b.HasOne("QuanLyHangHoa.Models.Customer", "Customer")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoice_Customer");

                    b.HasOne("QuanLyHangHoa.Models.StockOut", "StockOut")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("StockOutId")
                        .HasConstraintName("FK_SalesInvoice_StockOut");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("StockOut");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoiceLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("SalesInvoiceLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceLine_Product");

                    b.HasOne("QuanLyHangHoa.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceLine_Invoice");

                    b.HasOne("QuanLyHangHoa.Models.StockOutLine", "StockOutLine")
                        .WithMany("SalesInvoiceLines")
                        .HasForeignKey("StockOutLineId")
                        .HasConstraintName("FK_SalesInvoiceLine_StockOutLine");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("SalesInvoiceLines")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_SalesInvoiceLine_Unit");

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");

                    b.Navigation("StockOutLine");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustment", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany("StockAdjustmentApprovers")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_StockAdjustment_ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("StockAdjustmentCreators")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockAdjustment_CreatedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany("StockAdjustmentPosters")
                        .HasForeignKey("PostedBy")
                        .HasConstraintName("FK_StockAdjustment_PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockAdjustment_Warehouse");

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Poster");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustmentLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.StockAdjustment", "Adjustment")
                        .WithMany("Lines")
                        .HasForeignKey("AdjustmentId")
                        .IsRequired()
                        .HasConstraintName("FK_StockAdjustmentLine_Adjustment");

                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockAdjustmentLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockAdjustmentLine_Product");

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithMany("StockAdjustmentLines")
                        .HasForeignKey("ProductSerialId")
                        .HasConstraintName("FK_StockAdjustmentLine_ProductSerial");

                    b.Navigation("Adjustment");

                    b.Navigation("Product");

                    b.Navigation("ProductSerial");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockBalance", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockBalance_Product");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany("StockBalances")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockBalance_Warehouse");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockCountLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockCountLine_Product");

                    b.HasOne("QuanLyHangHoa.Models.StockCountSession", "Session")
                        .WithMany("Lines")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_StockCountLine_Session");

                    b.Navigation("Product");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountSession", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany("StockCountSessionApprovers")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_StockCountSession_ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("StockCountSessionCreators")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockCountSession_CreatedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany("StockCountSessionPosters")
                        .HasForeignKey("PostedBy")
                        .HasConstraintName("FK_StockCountSession_PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany("StockCountSessions")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockCountSession_Warehouse");

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Poster");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany("StockInApprovers")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_StockIn_ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("StockInCreators")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockIn_CreatedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany("StockInPosters")
                        .HasForeignKey("PostedBy")
                        .HasConstraintName("FK_StockIn_PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Supplier", "Supplier")
                        .WithMany("StockIns")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_StockIn_Supplier");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany("StockIns")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockIn_Warehouse");

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Poster");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockInLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockInLine_Product");

                    b.HasOne("QuanLyHangHoa.Models.StockIn", "StockIn")
                        .WithMany("Lines")
                        .HasForeignKey("StockInId")
                        .IsRequired()
                        .HasConstraintName("FK_StockInLine_StockIn");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("StockInLines")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_StockInLine_Unit");

                    b.Navigation("Product");

                    b.Navigation("StockIn");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockLedger", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany("StockLedgers")
                        .HasForeignKey("PostedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockLedger_PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockLedgers")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockLedger_Product");

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithMany("StockLedgers")
                        .HasForeignKey("ProductSerialId")
                        .HasConstraintName("FK_StockLedger_ProductSerial");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany("StockLedgers")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockLedger_Warehouse");

                    b.Navigation("Poster");

                    b.Navigation("Product");

                    b.Navigation("ProductSerial");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany("StockOutApprovers")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_StockOut_ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("StockOutCreators")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockOut_CreatedBy");

                    b.HasOne("QuanLyHangHoa.Models.Customer", "Customer")
                        .WithMany("StockOuts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_StockOut_Customer");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany("StockOutPosters")
                        .HasForeignKey("PostedBy")
                        .HasConstraintName("FK_StockOut_PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "Warehouse")
                        .WithMany("StockOuts")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockOut_Warehouse");

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("Poster");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockOutLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockOutLine_Product");

                    b.HasOne("QuanLyHangHoa.Models.StockOut", "StockOut")
                        .WithMany("Lines")
                        .HasForeignKey("StockOutId")
                        .IsRequired()
                        .HasConstraintName("FK_StockOutLine_StockOut");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("StockOutLines")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_StockOutLine_Unit");

                    b.Navigation("Product");

                    b.Navigation("StockOut");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockTransfer", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany("StockTransferApprovers")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_StockTransfer_ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Creator")
                        .WithMany("StockTransferCreators")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_StockTransfer_CreatedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "FromWarehouse")
                        .WithMany("StockTransfersFrom")
                        .HasForeignKey("FromWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockTransfer_FromWarehouse");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Poster")
                        .WithMany("StockTransferPosters")
                        .HasForeignKey("PostedBy")
                        .HasConstraintName("FK_StockTransfer_PostedBy");

                    b.HasOne("QuanLyHangHoa.Models.Warehouse", "ToWarehouse")
                        .WithMany("StockTransfersTo")
                        .HasForeignKey("ToWarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_StockTransfer_ToWarehouse");

                    b.Navigation("Approver");

                    b.Navigation("Creator");

                    b.Navigation("FromWarehouse");

                    b.Navigation("Poster");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockTransferLine", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Product", "Product")
                        .WithMany("StockTransferLines")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_StockTransferLine_Product");

                    b.HasOne("QuanLyHangHoa.Models.StockTransfer", "StockTransfer")
                        .WithMany("Lines")
                        .HasForeignKey("StockTransferId")
                        .IsRequired()
                        .HasConstraintName("FK_StockTransferLine_StockTransfer");

                    b.HasOne("QuanLyHangHoa.Models.Unit", "Unit")
                        .WithMany("StockTransferLines")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_StockTransferLine_Unit");

                    b.Navigation("Product");

                    b.Navigation("StockTransfer");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyClaim", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Approver")
                        .WithMany("WarrantyClaimApprovers")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_WarrantyClaim_ApprovedBy");

                    b.HasOne("QuanLyHangHoa.Models.AppUser", "Processor")
                        .WithMany("WarrantyClaimProcessors")
                        .HasForeignKey("ProcessedBy")
                        .IsRequired()
                        .HasConstraintName("FK_WarrantyClaim_ProcessedBy");

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithMany("WarrantyClaims")
                        .HasForeignKey("ProductSerialId")
                        .IsRequired()
                        .HasConstraintName("FK_WarrantyClaim_ProductSerial");

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ReplacementSerial")
                        .WithMany("WarrantyClaimReplacementSerials")
                        .HasForeignKey("ReplacementSerialId")
                        .HasConstraintName("FK_WarrantyClaim_ReplacementSerial");

                    b.HasOne("QuanLyHangHoa.Models.StockOut", "ReplacementStockOut")
                        .WithMany("WarrantyClaims")
                        .HasForeignKey("ReplacementStockOutId")
                        .HasConstraintName("FK_WarrantyClaim_ReplacementStockOut");

                    b.HasOne("QuanLyHangHoa.Models.WarrantyCoverage", "WarrantyCoverage")
                        .WithMany("WarrantyClaims")
                        .HasForeignKey("WarrantyCoverageId")
                        .IsRequired()
                        .HasConstraintName("FK_WarrantyClaim_Coverage");

                    b.Navigation("Approver");

                    b.Navigation("Processor");

                    b.Navigation("ProductSerial");

                    b.Navigation("ReplacementSerial");

                    b.Navigation("ReplacementStockOut");

                    b.Navigation("WarrantyCoverage");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyCoverage", b =>
                {
                    b.HasOne("QuanLyHangHoa.Models.Customer", "Customer")
                        .WithMany("WarrantyCoverages")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_WarrantyCoverage_Customer");

                    b.HasOne("QuanLyHangHoa.Models.ProductSerial", "ProductSerial")
                        .WithOne("WarrantyCoverage")
                        .HasForeignKey("QuanLyHangHoa.Models.WarrantyCoverage", "ProductSerialId")
                        .IsRequired()
                        .HasConstraintName("FK_WarrantyCoverage_ProductSerial");

                    b.HasOne("QuanLyHangHoa.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("WarrantyCoverages")
                        .HasForeignKey("SalesInvoiceId")
                        .HasConstraintName("FK_WarrantyCoverage_SalesInvoice");

                    b.Navigation("Customer");

                    b.Navigation("ProductSerial");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.AppUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("InverseCreator");

                    b.Navigation("PurchaseInvoices");

                    b.Navigation("SalesInvoices");

                    b.Navigation("StockAdjustmentApprovers");

                    b.Navigation("StockAdjustmentCreators");

                    b.Navigation("StockAdjustmentPosters");

                    b.Navigation("StockCountSessionApprovers");

                    b.Navigation("StockCountSessionCreators");

                    b.Navigation("StockCountSessionPosters");

                    b.Navigation("StockInApprovers");

                    b.Navigation("StockInCreators");

                    b.Navigation("StockInPosters");

                    b.Navigation("StockLedgers");

                    b.Navigation("StockOutApprovers");

                    b.Navigation("StockOutCreators");

                    b.Navigation("StockOutPosters");

                    b.Navigation("StockTransferApprovers");

                    b.Navigation("StockTransferCreators");

                    b.Navigation("StockTransferPosters");

                    b.Navigation("WarrantyClaimApprovers");

                    b.Navigation("WarrantyClaimProcessors");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Customer", b =>
                {
                    b.Navigation("SalesInvoices");

                    b.Navigation("StockOuts");

                    b.Navigation("WarrantyCoverages");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Product", b =>
                {
                    b.Navigation("ProductSerials");

                    b.Navigation("ProductUnit");

                    b.Navigation("PurchaseInvoiceLines");

                    b.Navigation("SalesInvoiceLines");

                    b.Navigation("StockAdjustmentLines");

                    b.Navigation("StockBalances");

                    b.Navigation("StockCountLines");

                    b.Navigation("StockInLines");

                    b.Navigation("StockLedgers");

                    b.Navigation("StockOutLines");

                    b.Navigation("StockTransferLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.ProductSerial", b =>
                {
                    b.Navigation("StockAdjustmentLines");

                    b.Navigation("StockLedgers");

                    b.Navigation("WarrantyClaimReplacementSerials");

                    b.Navigation("WarrantyClaims");

                    b.Navigation("WarrantyCoverage");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.SalesInvoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("WarrantyCoverages");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockAdjustment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockCountSession", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockIn", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("PurchaseInvoices");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockInLine", b =>
                {
                    b.Navigation("ProductSerials");

                    b.Navigation("PurchaseInvoiceLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOut", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("SalesInvoices");

                    b.Navigation("WarrantyClaims");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockOutLine", b =>
                {
                    b.Navigation("ProductSerials");

                    b.Navigation("SalesInvoiceLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockTransfer", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.StockTransferLine", b =>
                {
                    b.Navigation("ProductSerials");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Supplier", b =>
                {
                    b.Navigation("PurchaseInvoices");

                    b.Navigation("StockIns");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Unit", b =>
                {
                    b.Navigation("ProductUnits");

                    b.Navigation("Products");

                    b.Navigation("PurchaseInvoiceLines");

                    b.Navigation("SalesInvoiceLines");

                    b.Navigation("StockInLines");

                    b.Navigation("StockOutLines");

                    b.Navigation("StockTransferLines");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.Warehouse", b =>
                {
                    b.Navigation("ProductSerials");

                    b.Navigation("StockAdjustments");

                    b.Navigation("StockBalances");

                    b.Navigation("StockCountSessions");

                    b.Navigation("StockIns");

                    b.Navigation("StockLedgers");

                    b.Navigation("StockOuts");

                    b.Navigation("StockTransfersFrom");

                    b.Navigation("StockTransfersTo");
                });

            modelBuilder.Entity("QuanLyHangHoa.Models.WarrantyCoverage", b =>
                {
                    b.Navigation("WarrantyClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
